<?php

/**
 * Mapa das planilhas Punter (Google Sheets) importadas para o schema `punter`.
 * Fonte única lida tanto pelas migrations quanto pelo importador —
 * qualquer coluna nova na planilha precisa ser adicionada aqui antes de importar.
 *
 * Tipos suportados pelo ValueNormalizer: date, datetime_br, int, numeric, percent,
 * bool01 ("0.0"/"1.0" -> boolean), score ("2 x 0" -> [home,away]), text.
 */
return [

    'spreadsheets' => [
        'base_dados_nova' => [
            'id' => '1WH5N3qLvzbw5Vxkpv7TK5-u6xEpCZrZ0q3HWni9uTSo',
            'label' => 'Base de Dados nova 3.1_NOVAS LIGAS',
        ],
        'historico_lay' => [
            'id' => '1gbdkqzoRDSuV-0hDT5WrkW1Foa9rriztSGbiMjqDbrU',
            'label' => 'Histórico Lay 2x2 e Lay 0x1',
        ],
        'historico_partidas' => [
            'id' => '1ho1vc1AZ1y41I0Z-aBBmlG-9a5rg5r7rQLCH0GtqTA4',
            'label' => 'Histórico Partidas',
        ],
    ],

    'sources' => [

        'match_history' => [
            'label' => 'Histórico de Partidas',
            'spreadsheet' => 'historico_partidas',
            'sheet' => 'Historico_Base',
            'range' => null,
            'target' => 'match_history',
            'mode' => 'refresh',
            'natural_key' => ['data_hora_jogo', 'home_name', 'away_name', 'campeonato'],
            'columns' => [
                'Data_Hora_Jogo' => ['data_hora_jogo', 'date'],
                'home_name' => ['home_name', 'text'],
                'away_name' => ['away_name', 'text'],
                'homeGoalCount' => ['home_goal_count', 'int'],
                'awayGoalCount' => ['away_goal_count', 'int'],
                'totalGoalCount' => ['total_goal_count', 'int'],
                'resultado' => ['resultado', 'text'],
                'Pontos Casa' => ['pontos_casa', 'numeric'],
                'Pontos Visitante' => ['pontos_visitante', 'numeric'],
                'team_a_corners' => ['team_a_corners', 'int'],
                'team_b_corners' => ['team_b_corners', 'int'],
                'total_corners' => ['total_corners', 'int'],
                'BTTS' => ['btts', 'text'],
                'HTGoalCount' => ['htgoal_count', 'int'],
                'ht_goals_team_a' => ['ht_goals_team_a', 'int'],
                'ht_goals_team_b' => ['ht_goals_team_b', 'int'],
                'first_goal_time' => ['first_goal_time', 'numeric'],
                'first_goal_team' => ['first_goal_team', 'text'],
                'team_a_xg' => ['team_a_xg', 'numeric'],
                'team_b_xg' => ['team_b_xg', 'numeric'],
                'xG x Goals home' => ['xg_x_goals_home', 'numeric'],
                'xG x Goals away' => ['xg_x_goals_away', 'numeric'],
                'team_a_possession' => ['team_a_possession', 'numeric'],
                'team_b_possession' => ['team_b_possession', 'numeric'],
                'odds_ft_1' => ['odds_ft_1', 'numeric'],
                'odds_ft_x' => ['odds_ft_x', 'numeric'],
                'odds_ft_2' => ['odds_ft_2', 'numeric'],
                'odds_ft_over15' => ['odds_ft_over15', 'numeric'],
                'odds_ft_over25' => ['odds_ft_over25', 'numeric'],
                'Gols marcados até 15min (Casa)' => ['gols_marcados_ate_15min_casa', 'int'],
                'Gols marcados 16-30min (Casa)' => ['gols_marcados_16_30min_casa', 'int'],
                'Gols marcados 31-45min (Casa)' => ['gols_marcados_31_45min_casa', 'int'],
                'Gols marcados 46-60min (Casa)' => ['gols_marcados_46_60min_casa', 'int'],
                'Gols marcados 61-75min (Casa)' => ['gols_marcados_61_75min_casa', 'int'],
                'Gols marcados 76+min (Casa)' => ['gols_marcados_76_min_casa', 'int'],
                'Gols marcados até 15min (Visitante)' => ['gols_marcados_ate_15min_visitante', 'int'],
                'Gols marcados 16-30min (Visitante)' => ['gols_marcados_16_30min_visitante', 'int'],
                'Gols marcados 31-45min (Visitante)' => ['gols_marcados_31_45min_visitante', 'int'],
                'Gols marcados 46-60min (Visitante)' => ['gols_marcados_46_60min_visitante', 'int'],
                'Gols marcados 61-75min (Visitante)' => ['gols_marcados_61_75min_visitante', 'int'],
                'Gols marcados 76+min (Visitante)' => ['gols_marcados_76_min_visitante', 'int'],
                'Casa marca primeiro' => ['casa_marca_primeiro', 'bool01'],
                'Casa marca primeiro e vence no HT' => ['casa_marca_primeiro_e_vence_no_ht', 'bool01'],
                'Casa marca primeiro e vence no FT' => ['casa_marca_primeiro_e_vence_no_ft', 'bool01'],
                'Casa Reviravolta' => ['casa_reviravolta', 'bool01'],
                'Visitante marca primeiro' => ['visitante_marca_primeiro', 'bool01'],
                'Visitante marca primeiro e vence no HT' => ['visitante_marca_primeiro_e_vence_no_ht', 'bool01'],
                'Visitante marca primeiro e vence no FT' => ['visitante_marca_primeiro_e_vence_no_ft', 'bool01'],
                'Visitante Reviravolta' => ['visitante_reviravolta', 'bool01'],
                'Casa Ganhando até 30min' => ['casa_ganhando_ate_30min', 'bool01'],
                'Casa Ganhando até 30min e venceu no HT' => ['casa_ganhando_ate_30min_e_venceu_no_ht', 'bool01'],
                'Visitante Ganhando até 30min' => ['visitante_ganhando_ate_30min', 'bool01'],
                'Visitante Ganhando até 30min e venceu no HT' => ['visitante_ganhando_ate_30min_e_venceu_no_ht', 'bool01'],
                'Casa Ganhando até 60min' => ['casa_ganhando_ate_60min', 'bool01'],
                'Casa Ganhando até 60min e venceu no FT' => ['casa_ganhando_ate_60min_e_venceu_no_ft', 'bool01'],
                'Visitante Ganhando até 60min' => ['visitante_ganhando_ate_60min', 'bool01'],
                'Visitante Ganhando até 60min e venceu no FT' => ['visitante_ganhando_ate_60min_e_venceu_no_ft', 'bool01'],
                'Resultado_FT' => ['resultado_ft', 'text'],
                'Check Resultado' => ['check_resultado', 'text'],
                'Campeonato' => ['campeonato', 'text'],
                'Jogo Completo' => ['jogo_completo', 'text'],
                'game_week' => ['game_week', 'int'],
                'home_image' => ['home_image', 'text'],
                'away_image' => ['away_image', 'text'],
                'odds_1st_half_over05' => ['odds_1st_half_over05', 'numeric'],
                'Temporada' => ['temporada', 'text'],
                'odds_ft_under05' => ['odds_ft_under05', 'numeric'],
                'odds_ft_over05' => ['odds_ft_over05', 'numeric'],
                'odds_ft_under15' => ['odds_ft_under15', 'numeric'],
                'odds_ft_under25' => ['odds_ft_under25', 'numeric'],
                'odds_btts_yes' => ['odds_btts_yes', 'numeric'],
                'odds_btts_no' => ['odds_btts_no', 'numeric'],
                'odds_1st_half_under05' => ['odds_1st_half_under05', 'numeric'],
                'team_a_shotsOnTarget' => ['team_a_shots_on_target', 'int'],
                'team_b_shotsOnTarget' => ['team_b_shots_on_target', 'int'],
                'team_a_shotsOffTarget' => ['team_a_shots_off_target', 'int'],
                'team_b_shotsOffTarget' => ['team_b_shots_off_target', 'int'],
                'team_a_fouls' => ['team_a_fouls', 'int'],
                'team_b_fouls' => ['team_b_fouls', 'int'],
                'team_a_dangerous_attacks' => ['team_a_dangerous_attacks', 'int'],
                'team_b_dangerous_attacks' => ['team_b_dangerous_attacks', 'int'],
                'Diagnóstico Geral' => ['diagnostico_geral', 'text'],
                'Lay Casa' => ['lay_casa', 'text'],
                'Lay Fora' => ['lay_fora', 'text'],
                'Over' => ['over', 'text'],
                'Goleada Indica' => ['goleada_indica', 'text'],
                'P&L Lay Casa' => ['pnl_lay_casa', 'numeric'],
                'P&L Lay Fora' => ['pnl_lay_fora', 'numeric'],
                'P&L Gols 1.5' => ['pnl_gols_1_5', 'numeric'],
                'Primeiro Gol' => ['primeiro_gol', 'text'],
                'HT_primeiroGol' => ['ht_primeiro_gol', 'text'],
                'GouR HT Lay Fora' => ['gour_ht_lay_fora', 'text'],
                'GouR Lay Fora' => ['gour_lay_fora', 'text'],
                'GouR HT Lay Casa' => ['gour_ht_lay_casa', 'text'],
                'GouR Lay Casa' => ['gour_lay_casa', 'text'],
                'Saúde Greens Lay Fora' => ['saude_greens_lay_fora', 'text'],
                'Saúde Greens Lay Casa' => ['saude_greens_lay_casa', 'text'],
                'GouR Lay Goleada Casa' => ['gour_lay_goleada_casa', 'text'],
                'GouR Lay Goleada Casa HT' => ['gour_lay_goleada_casa_ht', 'text'],
                'Saúde Greens LG Casa' => ['saude_greens_lg_casa', 'text'],
                'GouR Lay Goleada Fora' => ['gour_lay_goleada_fora', 'text'],
                'GouR Lay Goleada Fora HT' => ['gour_lay_goleada_fora_ht', 'text'],
                'Saúde Greens LG Fora' => ['saude_greens_lg_fora', 'text'],
                'GouR Over 15FT' => ['gour_over_15_ft', 'text'],
                'GouR Over 05HT' => ['gour_over_05_ht', 'text'],
                'green _com _gols_15' => ['green_com_gols_15', 'bool01'],
                'green _com _over_05_HT' => ['green_com_over_05_ht', 'bool01'],
                'green _com _over_15_HT' => ['green_com_over_15_ht', 'bool01'],
                'GouR Under 25FT' => ['gour_under_25_ft', 'text'],
                'GouR Scalping Under 25FT' => ['gour_scalping_under_25_ft', 'text'],
                'Primeiros 15 Min' => ['primeiros_15_min', 'text'],
                'P&L Back Casa' => ['pnl_back_casa', 'numeric'],
                'GouR Over Back Casa' => ['gour_over_back_casa', 'text'],
                'P&L Back Fora' => ['pnl_back_fora', 'numeric'],
                'GouR Over Back Fora' => ['gour_over_back_fora', 'text'],
                'P&L Gols Under 0.5FT' => ['pnl_gols_under_0_5_ft', 'numeric'],
                'GouR Under 05FT' => ['gour_under_05_ft', 'text'],
                'P&L Gols Over 0.5FT' => ['pnl_gols_over_0_5_ft', 'numeric'],
                'GouR Over 0.5FT' => ['gour_over_0_5_ft', 'text'],
                'P&L Gols Under 1.5FT' => ['pnl_gols_under_1_5_ft', 'numeric'],
                'GouR Under 1.5FT' => ['gour_under_1_5_ft', 'text'],
                'P&L Gols Under 2.5FT' => ['pnl_gols_under_2_5_ft', 'numeric'],
                'P&L Gols Over 2.5FT' => ['pnl_gols_over_2_5_ft', 'numeric'],
                'GouR Over 2.5FT' => ['gour_over_2_5_ft', 'text'],
                'P&L BTTS Sim' => ['pnl_btts_sim', 'numeric'],
                'P&L BTTS Não' => ['pnl_btts_nao', 'numeric'],
                'GouR Over 0.5FT Tendencia' => ['gour_over_0_5_ft_tendencia', 'text'],
                'Media Pontos Casa Ate Data' => ['media_pontos_casa_ate_data', 'numeric'],
                'CV Média de Pontos Casa' => ['cv_media_de_pontos_casa', 'numeric'],
                'Media de Pontos Visitante' => ['media_de_pontos_visitante', 'numeric'],
                'CV Media de Pontos Visitante' => ['cv_media_de_pontos_visitante', 'numeric'],
                'Media Gols Total Casa' => ['media_gols_total_casa', 'numeric'],
                'CV Media de Gols Total Casa' => ['cv_media_de_gols_total_casa', 'numeric'],
                'Media Gols Total Visitante' => ['media_gols_total_visitante', 'numeric'],
                'CV Media de Gols Total Visitante' => ['cv_media_de_gols_total_visitante', 'numeric'],
                'Media Gols no 1T Casa' => ['media_gols_no_1t_casa', 'numeric'],
                'CV Media Gols no 1T Casa' => ['cv_media_gols_no_1t_casa', 'numeric'],
                'Media Gols no 2T Casa' => ['media_gols_no_2t_casa', 'numeric'],
                'CV Media Gols no 2T Casa' => ['cv_media_gols_no_2t_casa', 'numeric'],
                'Media Gols no 1T Visitante' => ['media_gols_no_1t_visitante', 'numeric'],
                'CV Media Gols no 1T Visitante' => ['cv_media_gols_no_1t_visitante', 'numeric'],
                'Media Gols no 2T Visitante' => ['media_gols_no_2t_visitante', 'numeric'],
                'CV Media Gols no 2T Visitante' => ['cv_media_gols_no_2t_visitante', 'numeric'],
                'Media Cantos Total Casa' => ['media_cantos_total_casa', 'numeric'],
                'CV Media de Cantos Total Casa' => ['cv_media_de_cantos_total_casa', 'numeric'],
                'Media Cantos Total Visitante' => ['media_cantos_total_visitante', 'numeric'],
                'CV Media de Cantos Total Visitante' => ['cv_media_de_cantos_total_visitante', 'numeric'],
                'Efic xG Casa' => ['efic_xg_casa', 'numeric'],
                'CV Efic xG Casa' => ['cv_efic_xg_casa', 'numeric'],
                'Efic xG Visitante' => ['efic_xg_visitante', 'numeric'],
                'CV Efic xG Visitante' => ['cv_efic_xg_visitante', 'numeric'],
                'Saldo de Gols Casa' => ['saldo_de_gols_casa', 'int'],
                'Saldo de Gols Visitante' => ['saldo_de_gols_visitante', 'int'],
                'Placar Casa Até 15 Min' => ['placar_casa_ate_15_min', 'int'],
                'Placar Casa Até 30 Min' => ['placar_casa_ate_30_min', 'int'],
                'Placar Casa Até 60 Min' => ['placar_casa_ate_60_min', 'int'],
                'Placar Casa Até 75 Min' => ['placar_casa_ate_75_min', 'int'],
                'Placar Visitante Até 15 Min' => ['placar_visitante_ate_15_min', 'int'],
                'Placar Visitante Até 30 Min' => ['placar_visitante_ate_30_min', 'int'],
                'Placar Visitante Até 60 Min' => ['placar_visitante_ate_60_min', 'int'],
                'Placar Visitante Até 75 Min' => ['placar_visitante_ate_75_min', 'int'],
                'Scalping Under' => ['scalping_under', 'text'],
                'Tendencia Over HT' => ['tendencia_over_ht', 'text'],
                'Tendencia Over 05FT' => ['tendencia_over_05_ft', 'text'],
            ],
        ],

        'column_dictionary' => [
            'label' => 'Dicionário de Dados',
            'spreadsheet' => 'historico_partidas',
            'sheet' => 'Dicionário de Dados',
            'range' => null,
            'target' => 'column_dictionary',
            'mode' => 'refresh',
            'columns' => [
                'Coluna' => ['column_label', 'text'],
                'Explicação' => ['description', 'text'],
            ],
        ],

        'panel_fixtures' => [
            'label' => 'Jogos Futuros do PAINEL',
            'spreadsheet' => 'base_dados_nova',
            'sheet' => 'Jogos Futuros do PAINEL',
            'range' => null,
            'target' => 'panel_fixtures',
            'mode' => 'refresh',
            'columns' => [
                'Date' => ['match_date', 'date'],
                'Nome Casa' => ['home_team', 'text'],
                'Nome Fora' => ['away_team', 'text'],
                'Jogos' => ['match_label', 'text'],
                'Classif Casa' => ['rank_home', 'int'],
                'Classif Geral Casa' => ['rank_home_overall', 'int'],
                'Classif Fora' => ['rank_away', 'int'],
                'Classif Geral Fora' => ['rank_away_overall', 'int'],
                'Match Odds' => ['match_odds_tendency', 'text'],
                'Escanteios' => ['corners_tendency', 'text'],
                'HT' => ['ht_tendency', 'text'],
                'Gols' => ['goals_tendency', 'text'],
                'Goleada_recom' => ['rout_recommendation', 'text'],
                'Diagnóstico Geral' => ['diagnosis', 'text'],
                'Liga' => ['league', 'text'],
                'Odd Abertura Casa' => ['opening_odd_home', 'numeric'],
                'Odd Abertura Empate' => ['opening_odd_draw', 'numeric'],
                'Odd Abertura Visitante' => ['opening_odd_away', 'numeric'],
                'Odd Abertura Over 1.5 FT' => ['opening_odd_over15_ft', 'numeric'],
                'Odd Abertura Over 2.5 FT' => ['opening_odd_over25_ft', 'numeric'],
                'Odd Abertura BTTS' => ['opening_odd_btts', 'numeric'],
            ],
        ],

        'bot_stats_until_apr2026' => [
            'label' => 'Resumo dos Robôs (until_apr2026)',
            'spreadsheet' => 'base_dados_nova',
            'sheet' => 'Records Bots até Abril2026',
            'range' => 'B3:F',
            'target' => 'bot_method_stats',
            'mode' => 'refresh',
            'extra' => ['block' => 'until_apr2026'],
            'columns' => [
                'Método' => ['method', 'text'],
                'Entradas' => ['entries', 'int'],
                'Greens' => ['greens', 'int'],
                'Reds' => ['reds', 'int'],
                'Win Rate' => ['win_rate', 'percent'],
            ],
        ],

        'bot_stats_after_apr2026' => [
            'label' => 'Resumo dos Robôs (after_apr2026)',
            'spreadsheet' => 'base_dados_nova',
            'sheet' => 'Records Bots 2.0 após Abril2026',
            'range' => 'B3:F',
            'target' => 'bot_method_stats',
            'mode' => 'refresh',
            'extra' => ['block' => 'after_apr2026'],
            'columns' => [
                'Método' => ['method', 'text'],
                'Entradas' => ['entries', 'int'],
                'Greens' => ['greens', 'int'],
                'Reds' => ['reds', 'int'],
                'Win Rate' => ['win_rate', 'percent'],
            ],
        ],

        'bot_entries_until_apr2026' => [
            'label' => 'Entradas dos Robôs (until_apr2026)',
            'spreadsheet' => 'base_dados_nova',
            'sheet' => 'Records Bots até Abril2026',
            'range' => 'H:R',
            'target' => 'bot_entries',
            'mode' => 'refresh',
            'extra' => ['block' => 'until_apr2026'],
            'columns' => [
                '↓↓↓ Histórico de todas as entradas até o momento ↓↓↓ id' => ['entry_id', 'text'],
                'data' => ['entry_date', 'date'],
                'campeonato' => ['league', 'text'],
                'time_1' => ['home_team', 'text'],
                'time_2' => ['away_team', 'text'],
                'odd' => ['odd', 'numeric'],
                'mercado' => ['market', 'text'],
                'resultado' => ['result', 'text'],
                'game_id' => ['game_id', 'text'],
                'filter_id' => ['filter_id', 'text'],
                'filter_name' => ['filter_name', 'text'],
            ],
        ],

        'bot_entries_after_apr2026' => [
            'label' => 'Entradas dos Robôs (after_apr2026)',
            'spreadsheet' => 'base_dados_nova',
            'sheet' => 'Records Bots 2.0 após Abril2026',
            'range' => 'H:R',
            'target' => 'bot_entries',
            'mode' => 'refresh',
            'extra' => ['block' => 'after_apr2026'],
            'columns' => [
                '↓↓↓ Histórico de todas as entradas até o momento ↓↓↓ id' => ['entry_id', 'text'],
                'data' => ['entry_date', 'date'],
                'campeonato' => ['league', 'text'],
                'time_1' => ['home_team', 'text'],
                'time_2' => ['away_team', 'text'],
                'odd' => ['odd', 'numeric'],
                'mercado' => ['market', 'text'],
                'resultado' => ['result', 'text'],
                'game_id' => ['game_id', 'text'],
                'filter_id' => ['filter_id', 'text'],
                'filter_name' => ['filter_name', 'text'],
            ],
        ],

        'league_summary' => [
            'label' => 'Resumo Histórico Punter',
            'spreadsheet' => 'base_dados_nova',
            'sheet' => 'Resumo Histórico Punter',
            'range' => 'B1:E',
            'target' => 'league_summary',
            'mode' => 'refresh',
            'columns' => [
                '' => ['league', 'text'],
                'Lay Fora' => ['lay_fora', 'numeric'],
                'Lay Casa' => ['lay_casa', 'numeric'],
                'Over' => ['over', 'numeric'],
            ],
        ],

        'lay_signals_historico' => [
            'label' => 'Histórico Lay 2x2 e Lay 0x1',
            'spreadsheet' => 'historico_lay',
            'sheet' => 'Base 2.0 Historica Lay2x2 e Lay',
            'range' => null,
            'target' => 'lay_signals',
            'mode' => 'merge_custom',
            'importer' => \App\Oracly\Punter\LaySignalsImporter::class,
            'expected_header' => ['Date', 'Country', 'League', 'Home', 'Away', 'FT_Odds_H', 'FT_Odds_D', 'FT_Odds_A', 'Radar', 'Placar Final', 'Check', 'Placar HT', 'Date Home x Away', 'Red 0x1 HT', 'Red 0x0 HT', 'Green Tranquilo 0x1', 'Green 0x0 HT 2x2', 'BTTS no HT 2x2', 'Leitura', 'Diagnóstico 0x1', 'Diagnóstico 2x2'],
        ],

        'lay_signals_atuais' => [
            'label' => 'Listas atuais Lay 2x2 e Lay 0x1',
            'spreadsheet' => 'base_dados_nova',
            'sheet' => 'Listas atuais Lay 2x2 e Lay 0x1',
            'range' => null,
            'target' => 'lay_signals',
            'mode' => 'merge_custom',
            'importer' => \App\Oracly\Punter\LaySignalsImporter::class,
            'expected_header' => ['Date', 'Country', 'League', 'Home', 'Away', 'FT_Odds_H', 'FT_Odds_D', 'FT_Odds_A', 'Link', 'Radar', 'Partida'],
        ],
    ],
];
